# Generated by Django 5.0.3 on 2025-12-05 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('datetime_start', models.DateTimeField()),
                ('location_name', models.CharField(max_length=200)),
                ('light_frames', models.PositiveIntegerField(default=0)),
                ('light_exposure_seconds', models.PositiveIntegerField(default=0)),
                ('iso', models.PositiveIntegerField(blank=True, null=True)),
                ('camera_model', models.CharField(max_length=100)),
                ('telescope_or_lens', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
