# Generated by Django 5.0.3 on 2025-12-06 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='target',
            field=models.CharField(default='None', max_length=200),
            preserve_default=False,
        ),
    ]
