# Generated by Django 5.0.3 on 2025-12-06 03:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_session_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='caption',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='session',
            name='post_creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
